services:
  api:
    build: .
    command: daphne -b 0.0.0.0 -p 8002 config.asgi:application
    volumes:
      - C:/Users/DELL/.cache/huggingface:/root/.cache/huggingface
      - .:/app
    ports:
      - "8002:8002"
    environment:
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=botify
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db

  db:
    image: ankane/pgvector:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=botify
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5434:5432"

volumes:
  postgres_data: 